<?php

namespace Poli\VotosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CancionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancionRepository extends EntityRepository
{
}
