<?php

namespace Poli\VotosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VotadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotadoRepository extends EntityRepository
{
}
